### ISSUE TITLE
Remaining progress time will stay as the last updated value even thou there is no program running.

### ISSUE THREAD

**Issue by emilp333** [DavidMStraub/homeassistant-homeconnect#6]
Remaining progress time will stay as the last updated value even thou there is no program running. 
Should be handled and reset to 0 or off if there is no running program.

**Comment by FlavorFx** [comment]
Same with my washing machine. Even when my BSH-App notify that cleaning is finished the adapter keeps last value >0. When my machine goes in standby the adapter changes from >0 to unavailable. Any change to improve it?

**Comment by DavidMStraub** [comment]
The problem is that this is not reported properly by the API in the SSE stream. The only way to handle this correctly would be constant polling, but they have quite strict rate limits, so I wanted to avoid that. The annoying things is that the app does not seem to be based on the same API, so it has more information/capabilities.
I already contacted the developers on some other issue and I might ask them about this as well (if/when they answer).

**Comment by FlavorFx** [comment]
I understand. Would it be helpful the check how the adapter from ioBroker works (https://github.com/dna909/ioBroker.homeconnect)? Of couse we both using HA but may be the source code tells us how this adapter works?

**Comment by DavidMStraub** [comment]
Possibly. Did you try that out to check how well it works? I never used ioBroker.

**Comment by emilp333** [comment]
Hi David,

As I mentioned in #5, I think the right way here is to do some logic in the code and reset it to 0 when you receive the event of program finished.

**Comment by Heiner1967** [comment]
Hi, same problem with my dischwasher, status of it often freeze wiht no update till restart of HA

**Comment by DavidMStraub** [comment]
Since the remaining progress time has been reimplemented as timestamp sensor, this problem is either solved (or still there in a different way, in which case we can open a new issue).
