### ISSUE TITLE
attribute current cavity temperature doesn't update 

### ISSUE THREAD

**Issue by h4nc** [DavidMStraub/homeassistant-homeconnect#61]
I added a sensor that tracks the attribute `current cavity temperature` of the oven switch entity. 

It seems like this attribute only gets updated when I restart ha, so this is probably a bug. 

Also it would be nice if the component could automatically add that temperature sensor, so it's not necessary to create a template sensor yourself.

**Comment by DavidMStraub** [comment]
AFAIK, the problem is that the cavity temperature is not reported by the event stream, but only when explicitly querying the API. This is done once at startup (to fetch the intitial status), but cannot be done regularly due to strict API rate limits. If I'm right (you can check the event stream response if there is something about the cavity temperature), this cannot be implemented at present.

Concerning the sensor, that's #38.

**Comment by h4nc** [comment]
That was fast, thanks. So I guess we have to close this. 

>  this cannot be implemented at present.

I hope I won't miss it, if it is available somewhen it future. Seeing the current temperature would be great.

**Comment by zfrank2601** [comment]
Dont understand this, with openhab3 there is no problem and cavitiy temperature is updating without api-problems..
At the moment I check an migration from openhab to ha, but there are so much limits and problems. Maybe I´ll stay on openhab.
