### ISSUE TITLE
Can't delete homeconnect integration

### ISSUE THREAD

**Issue by Minius90** [DavidMStraub/homeassistant-homeconnect#85]
After changing to homeconnect beta, I wanted to delete the homeconnect hacs integration (since home assistant added it to Core)

I just can't delete the integration. After rebooting the system it always states the following in notifications. How can I get rid of this entry?

> invalid config
The following integrations and platforms could not be set up:

homeconnect
Please check your config.

**Comment by DagBertelsen** [comment]
I had the same thing, took a while before i noticed this:
https://www.home-assistant.io/integrations/home_connect/

`home_connect:
  client_id: CLIENT_ID
  client_secret: CLIENT_SECRET`

previously this was called **homeconnect** now it's named **home_connect**. Try chaning that in your configuration.yaml

**Comment by sharkdp** [comment]
I also had some problems when upgrading to the new builtin integration because I wasn't able to properly remove the old (`homeconnect`) integration after I had already upgraded and uninstalled from HACS:

- Stop HA instance
- Update name to `home_connect` in `/config/configuration.yaml`
- Manually remove the integration and all devices from the files in `/config/.storage`. Use `grep homeconnect /config/.storage/*` to find all entries.
- Restart HA and set up the new builtin integration.

For those who haven't updated HA yet, I guess they should first properly remove the integration via the HA frontend (this is the part that didn't work for me), then uninstall from HACS, then update the YAML and upgrade HA.

**Comment by DagBertelsen** [comment]
@sharkdp when you mentioned it I did the same first, then noticed the change of `homeconnect` to `home_connect`

**Comment by DavidMStraub** [comment]
Looks like a duplicate of #79.

**Comment by Minius90** [comment]
Thanks for your support! Since I was afraid to delete something I should not, I left the entry till today. Updated my system to 0.111.3, tried it again - and succeeded in deleting it from the integration list.
